### ISSUE TITLE
Consider using git tags and releases

### ISSUE THREAD

**Issue by zaszi** [gnif/vendor-reset#2]
First of all, a massive thanks for providing this software. Fixing passthrough reset woes has never been easier.

In order to prevent manual installation and system pollution by using untracked packages, I am in the process of repackaging this as a DKMS module package for Arch Linux. However, this repository currently contains no tags or releases. Yet `dkms.conf` mentions a version `0.0.17`. Please consider using git tags for versioning and creating appropriate releases. This would make repackaging easier and offer more clarity for end-users.

Additionally, consider starting at version `0.1.0`. While the [semver](https://semver.org/) specification does not specifically forbid otherwise, this would adhere more to a common convention of how to version software in its early beginnings.

**Comment by gnif** [comment]
This project is literally a couple of weeks old and has issues we are still working on, most days being chopped and changed in large ways, it is nowhere near ready for a tag or a release version. When it is, 0.1.0 will be the first tag when we are ready.
