### ISSUE TITLE
Feature Request: Module Version for modinfo

### ISSUE THREAD

**Issue by netinetwalker** [gnif/vendor-reset#20]
@gnif ok not a bug but a feature request ... ;-P

In the module the Version number is missing. MODULE_VERSION is not set!
dkms use this information to replace the module if nessesarry. In my case it does not update the vendor-reset.ko 0.0.18 with the new 0.0.19 (audio reset branch).

_Originally posted by @netinetwalker in https://github.com/gnif/vendor-reset/issues/19#issuecomment-761620195_

**Comment by ajmadsen** [comment]
In master as of 547aec42c46fbd2dbfbefd9700e7b8a841d9ad5e
