### ISSUE TITLE
WX9100 question

### ISSUE THREAD

**Issue by labor4** [gnif/vendor-reset#32]
Hi

**I would be glad to get an idea** upfront, if the WX9100 has been tried before (or is assumed to be working), or known to **not** work at all.

It's a "Pro" variant and I don't know if they differ from Vega10.
I know there is the long way to find this out myself, please excuse my asking.

Thanks a lot

**Comment by gnif** [comment]
No idea sorry, nor am I aware of anyone that has reported if it does.
