### ISSUE TITLE
How to enable these options? Ubuntu 20.04

### ISSUE THREAD

**Issue by mk2016a** [gnif/vendor-reset#47]
Requirements
Ensure your kernel has the following options enabled:

CONFIG_FTRACE=y
CONFIG_KPROBES=y
CONFIG_PCI_QUIRKS=y
CONFIG_KALLSYMS=y
CONFIG_KALLSYMS_ALL=y
CONFIG_FUNCTION_TRACER=y

**Comment by mk2016a** [comment]
$ sudo sysctl -a | grep ftrace
kernel.ftrace_dump_on_oops = 0
kernel.ftrace_enabled = 1
$ sudo sysctl -a | grep kprobes
debug.kprobes-optimization = 1
$ sudo sysctl -a | grep quirks
$ sudo sysctl -a | grep kallsyms
net.core.bpf_jit_kallsyms = 0
$ sudo sysctl -a | grep tracer
kernel.stack_tracer_enabled = 0

**Comment by dev-sda1** [comment]
Ubuntu 20.04 should have them turned on by default.

**Comment by mk2016a** [comment]
Thanks, you are the god.
